In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv(r'CAR_DETAILS.csv',usecols=['name','seller_type','transmission','owner','fuel'])
df.head()

                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

Using Python

In [ ]:
df.drop('name',axis=1,inplace=True)

In [ ]:
df['transmission'] = df['transmission'].map({'Manual':0,'Automatic':1})

0       0
1       0
2       0
3       0
4       0
       ..
4335    0
4336    0
4337    0
4338    0
4339    0
Name: transmission, Length: 4340, dtype: int64

        fuel  seller_type  transmission         owner
0     Petrol            0             0   First Owner
1     Petrol            0             0   First Owner
2     Diesel            0             0   First Owner
3     Petrol            0             0   First Owner
4     Diesel            0             0  Second Owner
...      ...          ...           ...           ...
4335  Diesel            0             0  Second Owner
4336  Diesel            0             0  Second Owner
4337  Petrol            0             0  Second Owner
4338  Diesel            0             0   First Owner
4339  Petrol            0             0   First Owner

[4340 rows x 4 columns]

Using Scikitlearn

array([1, 1, 4, ..., 1, 1, 4], shape=(3472,))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.],
       ...,
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], shape=(3472, 3))