                       name  year  selling_price  km_driven    fuel seller_type transmission        owner
0             Maruti 800 AC  2007          60000      70000  Petrol  Individual       Manual  First Owner
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol  Individual       Manual  First Owner

   year  selling_price  km_driven
0  2007          60000      70000
1  2007         135000      50000

          year  selling_price  km_driven
0     0.535714       0.004505   0.086783
1     0.535714       0.012950   0.061988
2     0.714286       0.065315   0.123976
3     0.892857       0.025901   0.057028
4     0.785714       0.048423   0.174807
...        ...            ...        ...
4335  0.785714       0.043919   0.099181
4336  0.785714       0.043919   0.099181
4337  0.607143       0.010135   0.102900
4338  0.857143       0.095158   0.111579
4339  0.857143       0.023086   0.049590

[4340 rows x 3 columns]

0        60000
1       135000
2       600000
3       250000
4       450000
         ...
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

         year  km_driven
0    0.583333   0.226361
1    0.958333   0.074499
2    0.500000   0.116685
3    0.750000   0.401146
4    0.833333   0.169054
..        ...        ...
863  0.458333   0.169054
864  0.791667   0.340974
865  0.625000   0.111748
866  0.875000   0.015702
867  0.958333   0.083095

[868 rows x 2 columns]