In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
import sklearn as sk 
import seaborn as sk
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv(r'Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.drop('User ID',inplace=True,axis=1)
df.head()

KeyError: "['User ID'] not found in axis"

In [ ]:
df.head()

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

array([[-0.90453403,  0.80285749, -1.39649711],
       [-0.90453403,  1.93579072,  0.62530293],
       [-0.90453403, -0.76581929, -0.72256376],
       [-0.90453403,  0.97715491,  0.8703696 ],
       [-0.90453403, -0.67867058, -1.21269711],
       [-0.90453403, -0.59152187, -0.17116375],
       [-0.90453403,  0.8900062 ,  1.20733627],
       [-0.90453403, -0.67867058,  0.47213626],
       [ 1.1055416 ,  0.27996523,  0.22706959],
       [ 1.1055416 ,  0.45426265, -0.07926375],
       [-0.90453403, -0.15577832, -0.07926375],
       [-0.90453403,  1.41289846, -1.0288971 ],
       [-0.90453403, -1.20156284, -0.60003043],
       [-0.90453403, -1.46300897, -1.36586378],
       [ 1.1055416 , -0.59152187,  0.5946696 ],
       [ 1.1055416 , -0.15577832,  1.23796961],
       [-0.90453403,  1.32574975, -0.90636377],
       [-0.90453403,  0.80285749,  0.19643625],
       [ 1.1055416 ,  0.19281652, -0.78383043],
       [ 1.1055416 ,  1.67434459, -0.23243042],
       [-0.90453403, -1.28871155, -1.24333044],
       [ 1.1055416 , -0.67867058,  0.38023626],
       [ 1.1055416 ,  0.8900062 , -1.36586378],
       [-0.90453403,  1.93579072,  0.25770292],
       [ 1.1055416 , -1.55015768, -1.48839711],
       [ 1.1055416 ,  1.23860104, -1.36586378],
       [ 1.1055416 ,  0.45426265,  0.38023626],
       [ 1.1055416 ,  0.0185191 , -0.44686376],
       [-0.90453403,  1.58719588,  1.75873629],
       [-0.90453403, -1.55015768, -1.42713045],
       [-0.90453403,  0.80285749, -0.81446377],
       [ 1.1055416 , -1.55015768,  0.07390292],
       [ 1.1055416 , -0.06862961,  2.34076963],
       [ 1.1055416 , -0.76581929,  0.34960292],
       [ 1.1055416 ,  0.27996523,  1.20733627],
       [ 1.1055416 , -0.15577832,  0.22706959],
       [ 1.1055416 ,  0.0185191 , -0.38559709],
       [-0.90453403,  0.10566781, -0.07926375],
       [ 1.1055416 , -0.94011671, -1.15143044],
       [-0.90453403, -1.63730639,  0.01263625],
       [ 1.1055416 ,  0.97715491, -1.05953044],
       [-0.90453403, -1.11441413, -0.38559709],
       [ 1.1055416 , -1.63730639, -0.47749709],
       [ 1.1055416 ,  0.8900062 , -1.45776378],
       [ 1.1055416 , -1.46300897, -0.56939709],
       [-0.90453403,  0.62856007,  2.18760296],
       [ 1.1055416 , -0.67867058, -0.20179709],
       [-0.90453403, -0.50437316,  0.10453625],
       [ 1.1055416 ,  0.97715491, -0.81446377],
       [-0.90453403, -0.24292703, -0.7531971 ],
       [ 1.1055416 , -1.02726542,  0.34960292],
       [-0.90453403,  1.41289846,  0.44150293],
       [-0.90453403,  0.10566781, -0.38559709],
       [ 1.1055416 , -1.02726542,  0.38023626],
       [-0.90453403,  0.0185191 ,  0.38023626],
       [-0.90453403, -0.852968  , -1.12079711],
       [ 1.1055416 ,  2.02293943,  1.0541696 ],
       [-0.90453403, -0.94011671,  1.54430295],
       [ 1.1055416 , -0.50437316,  0.19643625],
       [ 1.1055416 , -0.50437316,  0.25770292],
       [-0.90453403,  0.36711394, -0.50813043],
       [-0.90453403, -0.15577832, -0.32433042],
       [-0.90453403,  1.32574975,  0.6865696 ],
       [-0.90453403, -0.76581929,  0.5946696 ],
       [ 1.1055416 , -0.76581929, -0.26306376],
       [-0.90453403, -0.852968  ,  2.12633629],
       [-0.90453403,  0.45426265,  0.6865696 ],
       [-0.90453403,  0.8900062 ,  2.34076963],
       [-0.90453403,  0.19281652, -0.26306376],
       [-0.90453403, -0.33007574,  1.39113628],
       [-0.90453403,  1.32574975,  2.15696963],
       [ 1.1055416 , -1.55015768,  0.53340293],
       [ 1.1055416 , -0.852968  , -0.29369709],
       [ 1.1055416 , -1.20156284, -1.45776378],
       [ 1.1055416 ,  0.8900062 , -1.0288971 ],
       [-0.90453403, -0.15577832, -0.53876376],
       [ 1.1055416 ,  1.67434459,  2.00380296],
       [-0.90453403,  1.50004717, -1.27396378],
       [-0.90453403, -0.15577832, -0.63066376],
       [-0.90453403,  0.0185191 ,  0.31896959]])

          Gender        Age  EstimatedSalary
count  80.000000  80.000000        80.000000
mean    0.450000  36.787500     67587.500000
std     0.500633  11.547035     32850.136793
min     0.000000  18.000000     19000.000000
25%     0.000000  28.000000     42750.000000
50%     0.000000  35.500000     65000.000000
75%     1.000000  47.000000     83500.000000
max     1.000000  60.000000    144000.000000

AttributeError: 'numpy.ndarray' object has no attribute 'describe'